/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R7RouteImport } from './routes/7'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogProjectsSlugRouteImport } from './routes/blog/projects/$slug'
import { Route as BlogPostsSlugRouteImport } from './routes/blog/posts/$slug'

const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R7Route = R7RouteImport.update({
  id: '/7',
  path: '/7',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogProjectsSlugRoute = BlogProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogPostsSlugRoute = BlogPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/7': typeof R7Route
  '/about': typeof AboutRoute
  '/components': typeof ComponentsRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/$slug': typeof BlogPostsSlugRoute
  '/blog/projects/$slug': typeof BlogProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/7': typeof R7Route
  '/about': typeof AboutRoute
  '/components': typeof ComponentsRoute
  '/blog': typeof BlogIndexRoute
  '/blog/posts/$slug': typeof BlogPostsSlugRoute
  '/blog/projects/$slug': typeof BlogProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/7': typeof R7Route
  '/about': typeof AboutRoute
  '/components': typeof ComponentsRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/posts/$slug': typeof BlogPostsSlugRoute
  '/blog/projects/$slug': typeof BlogProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/7'
    | '/about'
    | '/components'
    | '/blog/'
    | '/blog/posts/$slug'
    | '/blog/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/7'
    | '/about'
    | '/components'
    | '/blog'
    | '/blog/posts/$slug'
    | '/blog/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/7'
    | '/about'
    | '/components'
    | '/blog/'
    | '/blog/posts/$slug'
    | '/blog/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  R7Route: typeof R7Route
  AboutRoute: typeof AboutRoute
  ComponentsRoute: typeof ComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/7': {
      id: '/7'
      path: '/7'
      fullPath: '/7'
      preLoaderRoute: typeof R7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/projects/$slug': {
      id: '/blog/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/blog/projects/$slug'
      preLoaderRoute: typeof BlogProjectsSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/posts/$slug': {
      id: '/blog/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/blog/posts/$slug'
      preLoaderRoute: typeof BlogPostsSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogPostsSlugRoute: typeof BlogPostsSlugRoute
  BlogProjectsSlugRoute: typeof BlogProjectsSlugRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogPostsSlugRoute: BlogPostsSlugRoute,
  BlogProjectsSlugRoute: BlogProjectsSlugRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  R7Route: R7Route,
  AboutRoute: AboutRoute,
  ComponentsRoute: ComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
